# Generated by Django 4.2.6 on 2023-11-03 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_avatar_alter_user_id_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("76cc296c-36bc-48e3-8568-f4bdb9afe24c"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
