# Generated by Django 4.2.6 on 2023-11-03 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c2d75813-670f-4f1e-836d-6f5cd5473cd5"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
