# Generated by Django 4.2.6 on 2023-11-03 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("77899c4d-dd7e-4c14-98f5-0209ca5a6479"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
