# Generated by Django 4.2.6 on 2023-11-03 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1a8975d7-34e2-4d52-8198-17048708a837"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
