# Generated by Django 4.2.6 on 2023-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_sitedetail_unique_site_detail"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitedetail",
            name="unique_site_detail",
        ),
        migrations.AddConstraint(
            model_name="sitedetail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id__isnull", False)),
                fields=("id",),
                name="unique_site_detail",
            ),
        ),
    ]
