# Generated by Django 4.2.6 on 2023-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0004_remove_sitedetail_unique_site_detail_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitedetail",
            name="unique_site_detail",
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="maps_url",
            field=models.URLField(
                default="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
            ),
        ),
    ]
