# Generated by Django 4.2.6 on 2023-12-08 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0005_remove_sitedetail_unique_site_detail_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
    ]
