# Generated by Django 4.2.6 on 2024-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0007_sitedetail_unique_sitedetail"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitedetail",
            name="unique_sitedetail",
        ),
        migrations.AddConstraint(
            model_name="sitedetail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id__isnull", True), _negated=True),
                fields=("id",),
                name="unique_sitedetail",
            ),
        ),
    ]
