# Generated by Django 4.2.6 on 2024-01-08 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0008_remove_sitedetail_unique_sitedetail_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitedetail",
            name="unique_sitedetail",
        ),
    ]
